# Generated by Django 2.1.7 on 2019-03-17 15:46

from django.db import migrations, models
import imi_social.validators


class Migration(migrations.Migration):

    dependencies = [
        ('imi_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imistatus',
            name='content',
            field=models.CharField(max_length=150, validators=[imi_social.validators.validate_content]),
        ),
    ]
